export const courses = [
  {
    id: 1,
    title: 'Forex Trading Fundamentals',
    description: 'Learn the basics of Forex trading, including currency pairs, market analysis, and trading platforms.',
    duration: '6 weeks',
    level: 'Beginner',
    price: 'Free',
    isPaid: false,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
    lessons: [
      {
        id: 101,
        title: 'Introduction to Forex Markets',
        description: 'Learn about the basics of Forex markets and how they work',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: false,
      },
      {
        id: 102,
        title: 'Understanding Currency Pairs',
        description: 'Explore the major, minor, and exotic currency pairs',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: true,
      },
      {
        id: 103,
        title: 'Basic Technical Analysis',
        description: 'Learn how to read charts and identify patterns',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: true,
      },
    ],
    curriculum: [
      'Introduction to Forex Markets',
      'Understanding Currency Pairs',
      'Basic Technical Analysis',
      'Fundamental Analysis Basics',
      'Risk Management Principles',
      'Trading Psychology',
    ],
    requirements: [
      'No prior trading experience required',
      'Basic understanding of financial markets',
      'Computer with internet connection',
      'Dedication to learn',
    ],
    outcomes: [
      'Understand how the Forex market works',
      'Read and analyze currency charts',
      'Execute basic trading strategies',
      'Manage trading risks effectively',
      'Develop a trading plan',
    ],
  },
  {
    id: 2,
    title: 'Technical Analysis Mastery',
    description: 'Master technical analysis tools and indicators for better trading decisions.',
    duration: '8 weeks',
    level: 'Intermediate',
    price: '$199',
    isPaid: true,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=60',
    lessons: [
      {
        id: 201,
        title: 'Advanced Chart Patterns',
        description: 'Master complex chart patterns for better trade entries',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: false,
      },
      {
        id: 202,
        title: 'Technical Indicators in Depth',
        description: 'Learn how to use and combine multiple indicators',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: true,
      },
    ],
    curriculum: [
      'Advanced Chart Patterns',
      'Technical Indicators in Depth',
      'Price Action Trading',
      'Multiple Timeframe Analysis',
      'Trading Strategy Development',
      'Advanced Risk Management',
    ],
    requirements: [
      'Basic understanding of Forex trading',
      'Familiarity with trading platforms',
      'Understanding of basic technical analysis',
    ],
    outcomes: [
      'Master advanced technical analysis',
      'Develop complex trading strategies',
      'Identify high-probability trades',
      'Create custom indicators',
      'Build a comprehensive trading system',
    ],
  },
  {
    id: 3,
    title: 'Advanced Trading Strategies',
    description: 'Learn advanced trading strategies, risk management, and portfolio optimization.',
    duration: '10 weeks',
    level: 'Advanced',
    price: '$299',
    isPaid: true,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&auto=format&fit=crop&q=60',
    lessons: [
      {
        id: 301,
        title: 'Advanced Trading Concepts',
        description: 'Explore sophisticated trading methodologies',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: false,
      },
    ],
    curriculum: [
      'Advanced Trading Concepts',
      'Portfolio Management',
      'Algorithmic Trading Basics',
      'Advanced Risk Management',
      'Market Microstructure',
      'Professional Trading Practices',
    ],
    requirements: [
      'Strong understanding of technical analysis',
      'Previous trading experience',
      'Knowledge of trading platforms',
    ],
    outcomes: [
      'Implement advanced trading strategies',
      'Optimize trading portfolio',
      'Understand algorithmic trading',
      'Manage complex trading positions',
      'Trade like a professional',
    ],
  },
  {
    id: 4,
    title: 'Psychology of Trading',
    description: 'Understand trading psychology and develop a winning mindset.',
    duration: '4 weeks',
    level: 'All Levels',
    price: '$149',
    isPaid: true,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1579226905180-636b76d96082?w=800&auto=format&fit=crop&q=60',
    lessons: [
      {
        id: 401,
        title: 'Understanding Trading Psychology',
        description: 'Learn how psychology affects trading decisions',
        videoUrl: 'https://www.youtube.com/embed/buF-_3vNnh0?si=gLDXXWHAmg-BqW9C',
        locked: false,
      },
    ],
    curriculum: [
      'Understanding Trading Psychology',
      'Emotional Control in Trading',
      'Building Trading Discipline',
      'Developing a Trading Mindset',
      'Stress Management',
      'Peak Performance Trading',
    ],
    requirements: [
      'Open mindset to learn',
      'Willingness to self-reflect',
      'Basic trading knowledge',
    ],
    outcomes: [
      'Control trading emotions',
      'Develop trading discipline',
      'Build a winning mindset',
      'Handle trading stress',
      'Achieve peak performance',
    ],
  },
];